### ISSUE TITLE
Support Interface Material Disabling

### ISSUE THREAD

**Issue by doucettom** [supermerill/SuperSlicer#1055]
### Version
2.3.55.5

### Operating system type + version
Xubuntu 20.04

### Behavior
I'm trying to get rid of the arrowed part (see screenshot)
![169134236_2550491078589050_4453369825563727895_n](https://user-images.githubusercontent.com/6595645/113492108-7c3ec280-94a3-11eb-8fc3-4bb3928c3b98.jpg)

**Comment by neophyl** [comment]
You can’t currently. You can make it solid but you can’t stop it.

**Comment by dartrax** [comment]
This was fixed in PrusaSlicer 6f3f362.
It's not in the current stable yet, will hopefully be in the next version.
I hope @supermerill will merge this (soon ;-) ), because it's so hard to remove from build plate right now (PETG on PEI sheet for example...) that I can't use supports in Prusa at all.

**Comment by dartrax** [comment]
This is fixed in PrusaSlicer 2.4.0-alpha1

- Using the new "Snug" support style preference eliminates unneccessary overhanging of support which resulted in support structure on build platform as seen in the picture of @doucettom
- Using the new "First layer density" and "first layer expansion" preferences allow to reduce impact of those first layer support structures

**Comment by neophyl** [comment]
Its coming guys, Merill is working on the 2.4.1 merge in.  You can download an early version already but its a bit raw at the moment.  Still many issues so.....

**Comment by doucettom** [comment]
I'll still give it a spin and let you guys know what I find ! :)
