### ISSUE TITLE
Brim ears options counter intuitive

### ISSUE THREAD

**Issue by mrvanes** [supermerill/SuperSlicer#1397]
I find the Brim ears options either difficult to understand, or they don't do what they say they do.

**To Reproduce**
1. Load attached STL
2. Enable (default) Brim ears (125°, 1mm detection radius)

The result is brim ears on the sharp 90° corner, but I want brim ears on the rounded corners as well.
![image](https://user-images.githubusercontent.com/1901782/124766206-fe250880-df36-11eb-94e1-c4381e6f5787.png)

My intuition says: on a larger scale, these are just 90° corners as well, but it takes wider perspective (detection radius) to see that, so my first guess would be to increase detection radius.

3. Increase detection radius (to 30mm)
4. Nothing happens
5. Set detecion radius back to 1mm and Max angle to 160°

Now the brim ears appear on the rounded corners as well.
![image](https://user-images.githubusercontent.com/1901782/124766363-23197b80-df37-11eb-9593-fa56e8f2ed3b.png)

[Pot_Lid_Holders.zip](https://github.com/supermerill/SuperSlicer/files/6777375/Pot_Lid_Holders.zip)

**Expected behavior**
My understanding of Detection radius is not what it does, the same holds for Max angle.

**Desktop**
 - OS: Linux
 - Version 2.3.56.6

**Comment by neophyl** [comment]
My understanding of the description of the detection radius is that the setting is used to make it IGNORE small jagged areas that would otherwise cause a brim ear to be produced for tiny features in the model.  At least that's how interpret the geometry will be decimated before detecting sharp angles description.

So its working as how I would expect.
