### ISSUE TITLE
Preview does not show surface(s) to be ironed

### ISSUE THREAD

**Issue by laptop-laptop** [supermerill/SuperSlicer#1531]
**Describe the bug**

In Prusa Slicer, when ironing is activated, the preview shows the to-be-ironed surface(s) in light orange and the legend shows that. However, in SuperSlicer 2.2.53 and 2.3.56 (the two I tried), even I had Ironing selected under Infill->External patterns-Top, the preview does not show it and there is no ironing in the legend on the top left.

**To Reproduce**

As an example, I downloaded the cube and set Infill->External patterns->Top to Ironing. Then sliced the file.
Unlike Prusa Slicer, Legend on the top left does not list ironing as a Feature type and I cannot tell if the surface is to-be-ironed or not.

https://www.thingiverse.com/thing:1278865

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Version [e.g. 2.3.55.5], Use `Help->About`_

Windows 10. Versions 2.2.53 and 2.3.56

**Comment by supermerill** [comment]
that's because you used the ironing infill. It's not yet taggued as 'ironing' (but i may in the future, I'm not sure if it's useful, as it replace the top fill here)

If you want the same ironing as prusaslicer, use the post-process ironing (bottom of the fill tab) it's taggued as ironing and not top fill because it's on top of it instead of replacing it.

**Comment by laptop-laptop** [comment]
Thanks
