### ISSUE TITLE
Error on opening .stl file

### ISSUE THREAD

**Issue by saenglert** [supermerill/SuperSlicer#1906]
**Describe the bug**
When trying to open the cube.stl used in Teaching Techs calibration tutorial, SuperSlicer reports the error: `ERROR: First layer height can't be greater than max laye height` and the slice button says `Invalid data".

**To Reproduce**
1. Download the [file](https://teachingtechyt.github.io/files/cube.stl)
2. Open in SuperSlicer

**Project File**
See file above

**Expected behavior**
SuperSlice should be able to open and slice the file without error.

**Desktop**
 - OS: Ubuntu LTS 20
 - Version 2.3.57.5

**Additional context**
Using the same .stl in Cura works without any problems.

The only relating issue I could find was #1474, but the layer heights in my settings are not set to zero:
![grafik](https://user-images.githubusercontent.com/6491588/142244784-ad0e3ea1-45aa-4853-8aef-9983e8886af0.png)

Any help is greatly appreciated.

**Comment by supermerill** [comment]
Next time, save your project file (File -> save as). The stl is useless for me. And the screen shot doesn't tell the whole story.

You have your first layer height higher than 0.32mm. That's why he refuse to slice, as an extrusion can't be taller than wider.
It's in print settings -> slicing -> first layer height.

**Comment by saenglert** [comment]
Oh, ok. I thought you could start from the .stl file. Sorry then.

You are right, though. The setting for the first layer height is incorrect. Thank you very much for the help!
