### ISSUE TITLE
Print speed < 1mm/s for small perimeter while 60mm/s is set

### ISSUE THREAD

**Issue by Sverto** [supermerill/SuperSlicer#1948]
**Describe the bug**
With several prints I've noticed a perimeter speed of less than 1mm/s resulting in a failed print.
The default perimeter speed is set to auto.
The "small_perimeter_speed" value is set to 60mm/s.
Thin walls is turned off (in case it's relevant).
The minimum filament layer cooling speed is set to 10mm/s.

I've tried to find the cause and it seems that 'when a perimeter falls into the small_perimeter_speed category' its speed is reduced to < 1mm/s while the actual "small_perimeter_speed" value is set to 60mm/s. 

**To Reproduce**
1. Set perimeter speed to auto
2. Slice an object with a perimeter that falls into the small perimeter category
3. Notice the inexplicable slow speeds for these perimeters

**>> Project File <<**
[superslicer_bug.zip](https://github.com/supermerill/SuperSlicer/files/7583129/superslicer_bug.zip)

**Expected behavior**
The configured small perimeter speed value to be respected (or minimum layer cooldown speed).

**Screenshots**
![image](https://user-images.githubusercontent.com/9067382/142907643-0cfcfeb2-b50f-4b54-959f-830ede69569e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2.3.57.4

Could this be verified?
Thank you in advance.

**Comment by supermerill** [comment]
There is something weird.

**Comment by TokkenStrike** [comment]
Came here to see if anyone else had this issue.
I got the speed below 0.1mm/s and only noticed it when the printer actually stoped moving (at least I didn't see it move) in the middle of the print.
Also lowerging min length decrease the speed (was expecting it to increase but I may be wrong...), and matching min and max length use the right speed.

**Comment by supermerill** [comment]
Found the problem. I applied the slowdown below the '0' was replaced.

**Comment by afbenevides** [comment]
Hello, I know this one is closed, but I think I may be seeing the same/similar problem while on version 2.3.57.10_2022-02-03 (on OSX)

Maybe one of you can comment on that?

Here is what I get with different settings from 0, percentage % and mm/s setting. Maybe I did not understand well the auto functionality for this parameter and that it refers to another parameter that is wrong, but I hope someone can point me out where to look for that fix.

Would it be looking for the 0 mm/s (for auto parameter of perimeter_speed) for the speeds parameters in the top of same page instead of the resulting speed of the automatic calculated speed ?

Thanks in advance

0 (auto auto setting)
<img width="1258" alt="Capture d’écran, le 2022-02-10 à 10 45 27" src="https://user-images.githubusercontent.com/19934301/153445446-7c331b4a-e9d1-47f1-9848-a98f1a2530f1.png">
<img width="1225" alt="Capture d’écran, le 2022-02-10 à 10 46 18" src="https://user-images.githubusercontent.com/19934301/153445253-570ec07f-f633-4322-afe0-26a8cb1f972f.png">

50% setting
<img width="1428" alt="Capture d’écran, le 2022-02-10 à 10 46 38" src="https://user-images.githubusercontent.com/19934301/153445694-8aa80aae-e624-410f-b4f8-78fb6c555d18.png">
<img width="1278" alt="Capture d’écran, le 2022-02-10 à 10 48 51" src="https://user-images.githubusercontent.com/19934301/153445779-0949740f-cf54-4f6f-bb61-613dada34728.png">

50mm/s setting
<img width="1297" alt="Capture d’écran, le 2022-02-10 à 10 47 26" src="https://user-images.githubusercontent.com/19934301/153446120-5712eb8f-c881-4dd6-b7e5-8c5882b0e209.png">
<img width="1233" alt="Capture d’écran, le 2022-02-10 à 10 48 01" src="https://user-images.githubusercontent.com/19934301/153445951-825bd009-d7d3-4e8b-bf09-e19df274119b.png">

**Comment by supermerill** [comment]
@afbenevides can you post your project file?

**Comment by afbenevides** [comment]
[example_ultra_low_speed_small_peremeter.3mf.zip](https://github.com/supermerill/SuperSlicer/files/8042747/example_ultra_low_speed_small_peremeter.3mf.zip)

**Comment by Seafnox** [comment]
Still Have that issue on Version 2.5.59.2

With Default speed - 120 mm/s

When External perimeter speed is 50% - real speed in thin perimeter is 11.4
When External perimeter speed is 100% - real speed in thin perimeter is 12
When External perimeter speed is 500% - real speed in thin perimeter is 87
When External perimeter speed is 1000% - real speed in thin perimeter is 147

Small perimeter speed parametes is no weight on it (10%/50%/100%/500% - isn't matter)

![speed map](https://user-images.githubusercontent.com/2814050/224082517-608db0aa-7f00-4a42-abc3-22cd507c97ca.png)
![spped config](https://user-images.githubusercontent.com/2814050/224082532-b70d22f5-b9d1-4b33-9c1b-5a02da33359d.png)

**Comment by Seafnox** [comment]
Here my project
[Stacking_Box_-_0.5mm_wall_thickness.3mf.zip](https://github.com/supermerill/SuperSlicer/files/10933669/Stacking_Box_-_0.5mm_wall_thickness.3mf.zip)

**Comment by Seafnox** [comment]
Found the reasons - too high layer time brings to low printing speed
![image](https://user-images.githubusercontent.com/2814050/224554215-e8856fd1-dde6-449f-860b-a49b2f9525c4.png)
