### ISSUE TITLE
Volumetric flow rate seems stuck

### ISSUE THREAD

**Issue by nuxy69** [supermerill/SuperSlicer#1982]
**Describe the bug**
Even though everything is on automatic, the volumetric flow rate seems to be stuck at 10mm3/s

**To Reproduce**
1. Set all the speeds to 0
2. Set the volumetric flow rate on print settings and filament to 30

**Project file**
[Front_lead_screw_alignment_tool_v2.zip](https://github.com/supermerill/SuperSlicer/files/7624044/Front_lead_screw_alignment_tool_v2.zip)

**Expected behavior**
Volumetric flow rate should be 30 or close to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1516247/143931586-23b8ca05-0373-4e0d-81ed-a38671859ae9.png)
![image](https://user-images.githubusercontent.com/1516247/143931667-59febcf6-4bea-4fc5-b7db-c6d96383b159.png)
![image](https://user-images.githubusercontent.com/1516247/143931749-25493aa0-9254-4f47-8bbd-dc6b10d9e13e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.6

**Comment by neophyl** [comment]
Can you attach your saved 3mf project file (file>save project as) please.

**Comment by nuxy69** [comment]
Yes, ofcourse.. Sorry about that
[Front_lead_screw_alignment_tool_v2.zip](https://github.com/supermerill/SuperSlicer/files/7624043/Front_lead_screw_alignment_tool_v2.zip)
t.

**Comment by neophyl** [comment]
Don't set Gapfill speed to 0.  It doesn't work like the rest of the auto speeds. it even mentions it in the tooltip.  Set it to something reasonable like 20 or 30.  Doesn't really matter you can set it to 200 as long as its not 0.

Its always been an oddity.  It used to be setting it to zero was the only way of turning off gapfill.  Then a check box was added to turn it on/off.  At that point it was found that setting zero for its speed messed up the auto speed side of things.  That's why the tooltip specifically mentions setting to Zero will make it part of the autospeed calculation.

**Comment by nuxy69** [comment]
Ah, still the same behavior as PrusaSlicer then. Didn't see the tooltip as I imported all the settings. 
Will close this issue. Thanks @neophyl
