### ISSUE TITLE
Extrusion width and spacing

### ISSUE THREAD

**Issue by macchinette** [supermerill/SuperSlicer#2084]
### What happened?

I was trying to adapt the extrusion widths between the previous versions and the new ones and I realized that the default values given by the padlock were not correct compared to the previous versions.

2.3.57.8_2021-12-16 left photo ----------------------------------> 2.3.56.9 right photo
![image](https://user-images.githubusercontent.com/79080486/146680289-33f1bb45-543b-486c-aefd-fb7038506e3f.png)

![image](https://user-images.githubusercontent.com/79080486/146680320-1fab55eb-5c3a-44d3-85f7-f89fec15e6bd.png)

![image](https://user-images.githubusercontent.com/79080486/146680366-32e0cf68-b5b7-4b44-baf4-9bc5af5851af.png)

### Project file & How to reproduce

In addition, as can be seen from the project sliced into both versions at level 31, the path in the center of the two perimeters is strangely divided into segments, which does not happen by increasing the extrusion widths.

![image](https://user-images.githubusercontent.com/79080486/146681018-ee0676e7-6bb0-4251-acb6-d2e95f6d3ba8.png)
[2.3.57.8.zip](https://github.com/supermerill/SuperSlicer/files/7741073/2.3.57.8.zip)
[2.3.56.9.zip](https://github.com/supermerill/SuperSlicer/files/7741074/2.3.56.9.zip)

### Version

2.3.57.8_2021-12-16

### Operating system

Windows 10

### Printer model

Anycubic I3 Mega S

**Comment by supermerill** [comment]
First screenshot: there is some updates to make (yet) to the profile to remove these blue locks. Will do.
Second screenshot: forgot to check that 0 spacing will also do 0 width for the periemter & external perimeter. Will fix.
Third screenshot: this one is comparing apple an carrots, you didn't have the same settings activated in the left & right screenshot (see grey/black name, they are not the same).

extra question: This sis because the circles aren't circles but polygons. And the lines often didn't align, so there are thin spots and wide spots. That's why there is sometimes some problems. There is built-in mitigation system to try different width to use the best one, but it may fail, and it won't check a big amount of them.
