### ISSUE TITLE
wxWidgets GetItem Index out of Range

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2288]
### What happened?

SuperSlicer was idle in the background and through this error:

![image](https://user-images.githubusercontent.com/12439543/151855232-862fb2b7-a313-41ac-a056-e5f5f968e0e0.png)

### Project file & How to reproduce

[wxwidget.3mf.txt](https://github.com/supermerill/SuperSlicer/files/7973404/wxwidget.3mf.txt)

### Version

2.3.57.9

### Operating system

Windows 10 x64

**Comment by supermerill** [comment]
Can't reproduce. May be hard to diagnose.
Can you make this error message appear reliably? If yes, can you explain the steps to make it appear? Or I can give you a debug build that will output a more useful message.

I think this kind of things may appear when the screen change (like going from a 100% scale display to a 150% one), or something like that.

**Comment by feketeimre** [comment]
This happens every time i open the superslicer-gcodeviewer.exe. Although with a slightly different message:
![image](https://user-images.githubusercontent.com/15861028/183894670-9cb5822d-736b-4468-91d9-165aa7bfd4f9.png)


Might be unrelated but my hunch says otherwise: If i press continue im unable to load files. Gives the following error: The selected file ... does not contain a valid gcode.

**Comment by supermerill** [comment]
still here?

**Comment by feketeimre** [comment]
> still here?
Had the same problem with gcode viewer. But i realized it was an old release, 2.3.57.11 so i deleted my post.
Im sorry, i didnt meant to bump the issue.

**Comment by supermerill** [comment]
add a new message if it happens again in new versions.

**Comment by CCS86** [comment]
2.5.59.0

![image](https://user-images.githubusercontent.com/12439543/198776804-eb3f9f8c-dc69-486e-9dc1-e0846d6ef460.png)
