### ISSUE TITLE
Seam Position Error

### ISSUE THREAD

**Issue by Garryb123** [supermerill/SuperSlicer#2687]
A path starts on a corner when I had set the seam to 'rear'.

I expected all the loop starts to be in the rear and all were except this one.

[RFS_Sw_Jack_Mount.zip](https://github.com/supermerill/SuperSlicer/files/8467701/RFS_Sw_Jack_Mount.zip)

Windows 10
SS Version 2.3.57
Home made printer running Duet FW

![image](https://user-images.githubusercontent.com/5060580/162832029-8a35c530-0808-4494-a992-a5351c4446e2.png)

**Comment by supermerill** [comment]
seems fixed in 2.4
Won't fix the 2.3.

**Comment by Jamin82** [comment]
In the latest nightly I am getting odd seam behaviour:

if i set the seam position to rear i get the expected behaviour:
![image](https://user-images.githubusercontent.com/16251488/163178212-8d7b38e0-d183-4ccb-bd4f-193675f528ad.png)

if i manually set seam position it completely ignores the position of the orb
![image](https://user-images.githubusercontent.com/16251488/163178605-783a6c6f-a794-4c0d-b36a-412ff9f10c78.png)

![image](https://user-images.githubusercontent.com/16251488/163178656-758414a2-741c-4861-942c-d16c54b2b113.png)




[seam position error.zip](https://github.com/supermerill/SuperSlicer/files/8481337/seam.position.error.zip)

**Comment by supermerill** [comment]
> In the latest nightly I am getting odd seam behaviour:

found the bug (from the merge)
will be fixed in next nightly
