### ISSUE TITLE
bug Seem in Cylinder

### ISSUE THREAD

**Issue by Witawat** [supermerill/SuperSlicer#2706]
### What happened?

bug Seem in Cylinder
![image](https://user-images.githubusercontent.com/4926369/163408090-bbca40f8-0f6b-43b6-98a8-174f98b8fab2.png)
![image](https://user-images.githubusercontent.com/4926369/163408162-4083f460-15d7-4f16-b6a4-54e8e1374c6c.png)

if change  to rear
![image](https://user-images.githubusercontent.com/4926369/163408290-93d5b0a9-daae-4d26-9041-be1f07f212c5.png)
![image](https://user-images.githubusercontent.com/4926369/163408391-388ac84f-5aaa-4464-9101-de51ab02b0b3.png)

but prusa slicer not have
![image](https://user-images.githubusercontent.com/4926369/163408621-b2cb4327-7198-4ab7-ad61-1d292b7e48f1.png)

### Project file & How to reproduce

![image](https://user-images.githubusercontent.com/4926369/163408810-de55b2fc-8a19-4d68-b83e-b3310067455c.png)

### Version

2.4.58.2

**Comment by supermerill** [comment]
your project file?

**Comment by Witawat** [comment]
> your project file?
[bug.zip](https://github.com/supermerill/SuperSlicer/files/8493509/bug.zip)

**Comment by supermerill** [comment]
For the rear : I have the same as prusaslicer.
As it's using existing points, you can achieve a better alignment if you increase the precision (0.0125->0.002)
![image](https://user-images.githubusercontent.com/6536403/163556272-e546aeaf-9933-4e8c-ae16-f6d1d1756a62.png)


For the aligned, it's a bug I discovered some days ago, will be fixed in next nightly
