### ISSUE TITLE
Seam-sphere seams seem not saved with project

### ISSUE THREAD

**Issue by jhlchu** [supermerill/SuperSlicer#3153]
### What happened?

Seam positions added via seam-sphere are not loaded when project is re-opened. Seam positions from seam-sphere only apply in same session seam-sphere is added. Re-opening same project shows seam-sphere object still exists but seams revert back to what is specified in "Print Settings" instead. Seam-sphere seams seemingly seem not saved.

### Project file & How to reproduce

1. Create a project and add an *.stl.
2. Right-click *.stl and select "Add seam position" via context menu.
3. Place seam-sphere to where seams are desired. View sliced gcode preview to confirm.
4. Save project and close superslicer.
5. Re-open superslicer and open project.
6. Slice.
7. Seams are now ignoring seam-sphere location and default to whatever is set in "Print Settings"

### Version

2.5.59 Nightly

### Operating system

Win 10 Enterprise

**Comment by supermerill** [comment]
can't reproduce.
If you have a project that has an ignored seam-sphere on load+slice, give it to me.

**Comment by jhlchu** [comment]
## Project File
[Seam.zip](https://github.com/supermerill/SuperSlicer/files/9458620/Seam.zip)

## Seam sphere position
<img src="https://user-images.githubusercontent.com/5092505/187598262-23cce2ec-9237-4942-aa2e-bf521b7f7511.jpg" width="500">

## Correct seam in same session
<img src="https://user-images.githubusercontent.com/5092505/187598259-ae690c32-df8c-4d39-bd9e-47d7e8767968.jpg" width="500">

## New session, same file
<img src="https://user-images.githubusercontent.com/5092505/187598261-f6b8b33b-8238-4e3a-b921-4df5e077bae9.jpg" width="500">

**Comment by supermerill** [comment]
I can't extract your zip file, maybe there was an upload error?

**Comment by jhlchu** [comment]
This one is just the extension changed *.3mf to *.zip instead of compressing the *.3mf. 
## Project File
[90Deg.zip](https://github.com/supermerill/SuperSlicer/files/9467180/90Deg.zip)

**Comment by supermerill** [comment]
funny. I found this bug last February, and I fixed it. Now the root cause (loading modifier position) seems "fixed" and I need to remove the old fix.

**Comment by VanessaE** [comment]
This occurs in the Ubuntu 18.04 Appimage build also (2.5.59.0).

**Comment by VanessaE** [comment]
In fact, it happens with 2.5.59.2 as well.  Exactly as described by the parent. 
 I've attached a project file demonstrating it:

[Pneumatic Actuator (21828, plunger, with support structure).3mf.zip](https://github.com/supermerill/SuperSlicer/files/12094032/Pneumatic.Actuator.21828.plunger.with.support.structure.3mf.zip)

**Comment by VanessaE** [comment]
In this project, a correctly-placed seam would be dead center at the back of the support tower structure as well as the back of the round shaft of the plunger object, and that's more or less what I get if I place a seam object appropriately and slice (it's not entirely correct but it's close enough).

However, if I save, restart, reload, and slice again, the plunger object is still correct, but the support structure has the seam in the wrong place.  I wonder if it's because the support structure is not an independent object, but instead was loaded onto the plunger object as a "part"?

Note that I even have the global seam position set to "Rear" in this project, so there are two things telling the slicer to put the seam on the back side.
