### ISSUE TITLE
Raft Contact Z Distance Not Affecting Slicing

### ISSUE THREAD

**Issue by ruredi87** [supermerill/SuperSlicer#3259]
### What happened?

Whatever I set raft contact distance does not change anything. It has fixed gap and I can't change it 

### Project file & How to reproduce

[raft bug.zip](https://github.com/supermerill/SuperSlicer/files/9637089/raft.bug.zip)
![0 2](https://user-images.githubusercontent.com/79092546/192056604-ec007321-6662-4713-96d1-bad3b329b52f.png)
![0MM](https://user-images.githubusercontent.com/79092546/192056607-af154d18-2d8e-4db9-a9e9-18c757521584.png)

### Version

SuperSlicer_2.5.59.0_2022-09-13

### Operating system

Windows 11

### Printer model

Ender 3 v2

**Comment by neophyl** [comment]
Mmm your own pictures show a change.  The top picture has a gap between the bridge infill (light blue, looks like its printing at the default nozzle diameter=layer height so thicker than the normal layer height.  The bridge infill is the bottom of your print layers not the perimeters in this case due to your settings.

Your second picture shows the bridge infill touching the raft so no gap.  Clearly a change.  Seems to all be working normally.

**Comment by ruredi87** [comment]
> Mmm your own pictures show a change. The top picture has a gap between the bridge infill (light blue, looks like its printing at the default nozzle diameter=layer height so thicker than the normal layer height. The bridge infill is the bottom of your print layers not the perimeters in this case due to your settings.
> 
> Your second picture shows the bridge infill touching the raft so no gap. Clearly a change. Seems to all be working normally.

Thank you I could not see that
