### ISSUE TITLE
Top layer created despite "0" setting

### ISSUE THREAD

**Issue by vovodroid** [supermerill/SuperSlicer#3376]
### What happened?

Despite top soild layers set to zero it's still created:

![image](https://user-images.githubusercontent.com/8691781/198215316-11cc640d-1c46-4ab8-b3aa-a0868dba666b.png)

If Infill is set to 0 just external perimeter is printed:

![image](https://user-images.githubusercontent.com/8691781/198215562-61568da7-8c38-45de-a800-613f772cd607.png)

### Project file & How to reproduce

[Merged.zip](https://github.com/supermerill/SuperSlicer/files/9876626/Merged.zip)

### Version

Version 2.4.58.5 (nightly_dev as well)

### Operating system

Wn10 x64

### Printer model

Biqu B1 SE

**Comment by neophyl** [comment]
Its not top infill really its internal infill.  You are changing the infill % and the amount changes.  Even on the key when sliced its labelled up as internal infill.  
It is because you have Print Settings>Perimeters & Shell>Quality> Only One perimeter > On Top Surfaces enabled.  The lower layers have sufficient perimeter count to preclude the use of any infill.  On the top because of that option there is only one perimeter allowed so it has room for infill, which is what it is doing.  Infill NOT topfill.

No issue here, its just doing what you have configured.

**Comment by vovodroid** [comment]
Indeed. Superslicer has quite sophisticated configuration)))
Thanks!
