### ISSUE TITLE
Crashes on save (project)

### ISSUE THREAD

**Issue by MaurolepisDreki** [supermerill/SuperSlicer#3927]
### What happened?

SuperSlicer crashes when I try to save any but the most trivial projects, resulting in file corruption.

Debug log reports:
```
10:07:39 AM: Debug: Adding duplicate image handler for 'JPEG file'
[2023-09-01 10:07:39.980954] [0x00007fac765ff6c0] [error]   Unable to open connection to spacenavd
10:07:40 AM: Debug: Unrecognized accel key 'Dèl', accel string ignored.
10:07:40 AM: Debug: "Shift+Tab" is not supported as a keyboard accelerator with GTK
10:07:48 AM: Debug: window wxTreeCtrl(0x56520e4549d0) lost focus even though it didn't have it
10:07:48 AM: Debug: window wxTreeCtrl(0x56520e4549d0) lost focus even though it didn't have it
10:07:48 AM: Debug: window wxTreeCtrl(0x56520e4549d0) lost focus even though it didn't have it
10:07:48 AM: Debug: window wxTreeCtrl(0x56520e4549d0) lost focus even though it didn't have it
10:07:48 AM: Debug: window wxTreeCtrl(0x56520e4549d0) lost focus even though it didn't have it
10:07:48 AM: Debug: window wxTreeCtrl(0x56520e4549d0) lost focus even though it didn't have it
superslicer: /usr/src/debug/superslicer/SuperSlicer/src/libslic3r/Format/3mf.cpp:3191: bool Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(mz_zip_archive&, const Slic3r::Model&, const Slic3r::DynamicPrintConfig&, const IdToObjectDataMap&, const std::string&): Assertion `false' failed.
Aborted (core dumped)
```

NOTE: This issue does not seem to be infill pattern specific.  It did the same thing on the gyroid pattern (preferred) before I started working backwards through the steps to find the earliest fail-point (default pattern: stars).

### Project file & How to reproduce

[allinfo.zip](https://github.com/supermerill/SuperSlicer/files/12499951/allinfo.zip)
(core dump included)

To reproduce:
1. Import the STL file into a new SuperSlicer project
2. Use the model's drop-down menu (right panel) to add a custom infill for the object.
3. Attempt to save the project (e.g. `File > Save Project' for new project, or CTRL+S for existing project, &c.)

### Version

2.4.58.5

### Operating system

Arch Linux (Linux 6.4.12-arch1-1 x86_64

### Printer model

Voxlab Aquila C2

**Comment by supermerill** [comment]
I guess it's the place where i added some logging, but the conditions wasn't right. Should be fixed in the last nightly.

long explanation:
. sometimes, a pattern isn't correctly saved in the project file. But i never was able to reproduce.
. so i instrumented the saving code to double-check for these.
. as the assert are disabled in the release, i added a assert(false) here so it will stop a debug build so i know when it's failaing, to investigate.
. problem: the arch linux build (not by me) doesn't disable the assert. I have no control over it.

Please tell the people that support the arch linux build to disable assert in release mode.
