### ISSUE TITLE
2.5.59.3 causes older versions to crash when viewing cooling settings

### ISSUE THREAD

**Issue by Alohacajun** [supermerill/SuperSlicer#3976]
### Fix: Delete %AppData%/SuperSlicer/ui_layout
**Bug description**
If you run 2.5.59.3 and switch back to an older version (ie 2.5.59.2), opening Filament > Cooling will cause it to crash.

**Expected behavior**

**To Reproduce**
1. Run 2.5.59.3, then close.
2. Run 2.5.59.2
3. Open Filament tab
4. Open cooling options
5. Crash

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.5.59.3 / 2.5.59.2

**Additional context**
_This might happen because all my versions share the same AppData config folder._
Is this related to the "Rework of fan speed control by extrusion type." in 59.3?

**Comment by legend069** [comment]
Yes this is most likely due to the fan speeds rework.

Not sure why it would crash though, unless it's unhappy with extra variables in the config.

**Comment by Alohacajun** [comment]
Would it be viable to have alpha/beta/RC builds use their own AppData directory? They do this in the PS repo as seen [here](https://github.com/prusa3d/PrusaSlicer/releases?page=2).

**Comment by Darkmann12** [comment]
I have also run into this :)

**Comment by legend069** [comment]
@supermerill 
would it be worth while reverting the variables that were changed back to original?
or adjusting code so any old variable names are still loaded from the config but get assigned to the new variable names?
ie `overhang_perimeter_fan_speed  = overhangs_fan_speed`


also https://github.com/supermerill/SuperSlicer/issues/3991

**Comment by supermerill** [comment]
The issue comes from the ui layout.
The layout used is the last one, but with an old version, there can be empty lines, where the settings doesn't exists yet.
And currently, there is a bug with a crash when there is an empty line.
I fixed it, and next version will have the patch.
I'll patch the 2.5 and future 2.7
For the 2.4, I'm not sure it's that useful, tell me.

To manually fix the issue: before using an old version, delete the ui_layout directory from your configuration directory.
The way it's updated is really subpar, i'll work a bit on that right now to avoid future problem with it.
