### ISSUE TITLE
Brim speed is set to 50% of "bridge speed"

### ISSUE THREAD

**Issue by trampas** [supermerill/SuperSlicer#4050]
### What happened?

Trying to set brim speed and found out that it appears to be hard coded to 50% of bridge speed.  

### Project file & How to reproduce

Set the default speed to 100mm/s set all the other speeds to 100% change the first layer speed to 0 for min and 100% for the max.  Slice a print with brim.  Look at the speeds in the Gcode preview window.  The brim speed will be 50mm/s.  change the bridge speed to 200% slice again, look at brim speed notice that it is now 100mm/s

### Version

2.5.59

### Operating system

windows 11

### Printer model

voron 2.4 with stealthburn

**Comment by supermerill** [comment]
It was applied after it was used...
Now fixed, it's applied at the start, so no other problems with other settings.
I also changed some things:
 . now it's a modifier for object, not a region as it makes no sense because brim and skirt are global or object-defined.
 . global skirt/brim will use the global setting, and only the brim/skirt that are object-specific (sequential print) use the object modifiers.
