### ISSUE TITLE
Ender 3 profile contains the wrong bed size

### ISSUE THREAD

**Issue by soggywhale** [supermerill/SuperSlicer#4247]
### What happened?

when I tried to calibrate the bed I noticed that the default ender 3 profile has a bed size of 225mm X 225mm while the correct one
is 220x220.

### Project file & How to reproduce

[First layer calibration.zip](https://github.com/supermerill/SuperSlicer/files/15199691/First.layer.calibration.zip)

### Version

2.4.58.5

### Operating system

NixOS

### Printer model

Ender 3 Pro

**Comment by anonymousaga** [comment]
An ender 3's bed is 235x235mm. Some slicers have defaulted to a 7.5mm unprintable border on the edges of the bed (220x220mm). Superslicer defaults to a 5mm unprintable border (225x225mm). 5mm is plenty of margin, especially since the ender 3's nozzle is able to reach beyond all edges of the bed.

Please close this issue if this response satisfies you.
