### ISSUE TITLE
Estimate time of completion for sliced files

### ISSUE THREAD

**Issue by GalvanicGlaze** [supermerill/SuperSlicer#4275]
Any chance we could get a line added under the total printing time for a sliced file to say what time it's expected to finish?

![Untitled](https://github.com/supermerill/SuperSlicer/assets/79122142/85e47843-10f4-4e4a-b0fe-252d103e411d)

**Comment by neophyl** [comment]
How ?  You could start the print of the gcode file at any point after its sliced.  The SLICER has no idea when that will be.  Could be  a minute, and hour, 3 weeks etc.  Just because its been sent to a printer that does not mean its going to start the print.

Finish time is a function of your printer firmware.  It knows when it started, it knows the total time to print and so if it has a real time clock then it can tell you when it should finish.

**Comment by GalvanicGlaze** [comment]
> How ? You could start the print of the gcode file at any point after its sliced. The SLICER has no idea when that will be. Could be a minute, and hour, 3 weeks etc. Just because its been sent to a printer that does not mean it's going to start the print.
> 
> Finish time is a function of your printer firmware. It knows when it started, it knows the total time to print and so if it has a real time clock then it can tell you when it should finish.

Yeah , I would hope common sense would prevail

I always slice my files and send them directly to the printer to print with the upload and print button in SS.
Everyday when I print and I want the print to end at a certain time so I can swap the plate out before bed or before I go to work I need to work out what time it would finish and then I add or remove parts to get the timing right. 

I want an option for it to take the current time and add the approximate print time and tell what time it would finish if I sent it now with a hot printer ready to go, same thing I have to work out myself currently.

**Comment by krautech** [comment]
I agree, as simple of an addition this is, itd be great. I also upload + print directly to printer and having this would be great. I could easily see an ETA and know what time itd finish for the same reasons.
