### ISSUE TITLE
Setting: XY Compensation is reversed

### ISSUE THREAD

**Issue by madejackson** [supermerill/SuperSlicer#4276]
**Bug description**
in 2.5.59.10, The Setting "XY Compensation" is reversed. See Printscreen for comparison with Version 2.5.59.6

**Expected behavior**
Extrusion / hole should be shrunk instead of expanded.

!!>> Project File <<!!
[D0_bearing_based_spirographic_WDT_tool_2024_14.zip](https://github.com/supermerill/SuperSlicer/files/15431013/D0_bearing_based_spirographic_WDT_tool_2024_14.zip)

**Screenshots**
Comparison between Versions:
![grafik](https://github.com/supermerill/SuperSlicer/assets/24832654/0c74730b-ac8b-4ccb-bcc0-43e613873c45)

**Desktop:**
 - OS: Windows
 - Version 2.5.59.10

**Comment by CuredPrusa** [comment]
As SuperMeril explain to me once, "minus" means shaving off the perimeter material.  Inside or outside. 
And yes, this doesn't match the actual descriptive text (mouse hover).
And yes, some other versions reverse that for I don't know what reason. 

That's why this function is on my check list as one of important functions which have to be checked when testing a new version.
That's why I always save my projects with SS version number in project's name (file name). Until I find additional time and energy to test new SS version on old project, I use the version in which project was conceived.  It is tedious, but what can you do.  Guys (developers) play the music, we just dance. 

Prusa still doesn't have hole correction. But in Prusa and Cura "+" means enlarge (enlarge hole or enlarge outer surface) and that is logical. Or it became logical. In Super Slicer we have something Super 👯 :)

**Comment by supermerill** [comment]
> As SuperMeril explain to me once, "minus" means shaving off the perimeter material. Inside or outside. **And yes, this doesn't match the actual descriptive text (mouse hover)**. And yes, some other versions reverse that for I don't know what reason.
> 

Where is the descriptive text problem? can't spot it myself.

> Prusa still doesn't have hole correction. But in Prusa and Cura "+" means enlarge (enlarge hole or enlarge outer surface) and that is logical. Or it became logical. In Super Slicer we have something Super 👯 :)

the '-' -> remove material and '+' -> add material was taken from prusa's xy compensation.

**Comment by supermerill** [comment]
@madejackson I fix the direction, there was a problem in a previous version, where the + and - where inverted.
it's the outer or the inner setting that bother you?

**Comment by CuredPrusa** [comment]
Hi Super! :)
Here it is:
![image](https://github.com/supermerill/SuperSlicer/assets/98842248/7e16e962-42e2-4d44-88db-5a464d1b174f)
It says negative inwards positive outwards.
If you relate that to a hole, it means negative is pushing the hole inwards, meaning the hole will become smaller.  
But we used to do it the opposite, because that's how it works.

**Comment by madejackson** [comment]
Yes, i think it's only the Inner one that's reversed.

**Comment by supermerill** [comment]
> He means the hover popup text. The settings behaviour doesn't align it's description, it's reversed.

I fail to see how it's reversed. Maybe my wording is bad.
I can change them to something else, maybe 'inward' and 'outward' are confusing.
'inward' here means 'from unprinted area to the printed area'

so for a hole, inward means that the hole will grow as the hole grow into the printed area.

Do you have any idea for a better wording?

**Comment by madejackson** [comment]
IMHO the description itself is fine. At least I understand it. Only that it actually does it the other way around in the latest version.

**Comment by CuredPrusa** [comment]
>the '-' -> remove area and '+' -> add area was taken from prusa's xy compensation.

Yes, but Prusa doesn't have inner and outer wall separated, that's the catch!

**Comment by CuredPrusa** [comment]
The logic from everyday life is simple:
I want to enlarge the hole, I go to hole settings and enlarge it with "plus".
I want to enlarge the outer contour, I go to outer settings and enlarge it with "plus".

But here we have something different - the hole is enlarged with "minus". And that could be fine too as long as we get used to it and it should stays CONSISTANT within all versions otherwise it could get really confusing. And instruction text should be better defined.

**Comment by madejackson** [comment]
Yeah I see now how the description can be interpreted both ways...

**Comment by supermerill** [comment]
I addad 'add /remove area' to the tooltip. Should be a bit easier now to understand.

> but Prusa doesn't have inner and outer wall separated, that's the catch!

Put the same value on both, to have the same result as in prusaslicer.

>  it should stays CONSISTANT within all versions otherwise it could get really confusing. And instruction text should be better defined.

Agree.
