### ISSUE TITLE
Support material - offset as percentage of layer height instead of extrusion width

### ISSUE THREAD

**Issue by towe96** [supermerill/SuperSlicer#463]
### Version
2.2.53.1

### Operating system type + version
Windows 10 64-bit 2004

### 3D printer brand / version + firmware version (if known)
Tronxy X5S on Klipper (not relevant)

### Behavior
When setting up support structure generation for FDM printers, the tooltip for the Z offset reads
"Can be a % of the extruding width used for the interface layers."
for the Top and Bottom offsets.

This seems counter-intuitive - why would a vertical distance be dependent on an extrusion width?
The tooltip, and likely the underlying code, should be modified to use a percentage of the base layer height instead, rounding up and down to full layers. Alternatively, a number of layers could be specified directly.

This seems similar to the age-old bug in Slic3r and PrusaSlicer where an extrusion width set as a percentage would be calculated over layer height, rather than nozzle diameter.

**Comment by supermerill** [comment]
because over the interface (or the interfce itself if it's a bottom one) have to be printed mostly in the air.
Because of that, it's a "bridge flow", ie it'a a round filament extrusion.
Because of that, it's only a factor of the nozzle width. Layer height is irrelevant.
As I don't have access to the nozzle, bu it have access to the extrusion width (wich should be close enough), it can be a % of the extrusion width.
