### ISSUE TITLE
Bed temp not set by slicer w/ Klipper g-code flavor

### ISSUE THREAD

**Issue by ProfEngr** [supermerill/SuperSlicer#485]
### Version
2.2.53

### Operating system type + version
Win 7

### 3D printer brand / version + firmware version (if known)
Ender 3 modded
Klipper, updated this week

### Behavior
Bed temp g-code (M140 or M190) is not being injected into the file when Klipper g-code flavor is selected in Printer tab. 50C is set in the Filament tab. Is this a feature, a bug, or setting I missed in a tab?

**Comment by supermerill** [comment]
Put it on the start-gcode.
It's because klipper use of macros and so it won't add it by itself to avoid conflicts. Most klipper user prefer to write `PRINT_START EXTRUDER_TEMP=[first_layer_temperature] BED_TEMP=[first_leyer_bed_temperature]`

Now that i think of it, I can return to legacy behaviorthat if there is nothing on start gcode.
