### ISSUE TITLE
Supporting Dense Layer too aggressive. 

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#546]
Latest version (happened in previous ones too, I think...

![image](https://user-images.githubusercontent.com/36974632/95482539-2a026600-0986-11eb-9c93-f8e31344b130.png)

Infill "supporting dense layer" is way too keen. It covers the whole interior every few layers (between five and 15), sometimes even with five or six layers of "Bridge infill". It only really needs to do this towards the edge, and surely not so many layers at a time!

**Comment by LaserBee** [comment]
![image](https://user-images.githubusercontent.com/36974632/95483097-bb71d800-0986-11eb-9e15-3b641645c1a9.png)
![image](https://user-images.githubusercontent.com/36974632/95483129-c75d9a00-0986-11eb-9a56-b23932733896.png)

**Comment by liftbag** [comment]
Have you tried selecting "Anchored" rather than "Automatic"?

Automatic

<img width="1745" alt="Schermata 2020-10-08 alle 18 43 49" src="https://user-images.githubusercontent.com/14921654/95488850-57efa680-0996-11eb-8b44-3340e507a12b.png">



Anchored

<img width="1745" alt="Schermata 2020-10-08 alle 18 44 23" src="https://user-images.githubusercontent.com/14921654/95488897-6473ff00-0996-11eb-8df2-747923cbba6c.png">

**Comment by supermerill** [comment]
there is now more options and the algo is refined.
