### ISSUE TITLE
Restrict Fan Startup Delay to bridge fan only.

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#595]
### Version
Latest
Inconsistent Fanspeed results for external perimeter.

![image](https://user-images.githubusercontent.com/958490/96869072-44047400-146f-11eb-8934-11add8757e3a.png)
![image](https://user-images.githubusercontent.com/958490/96869117-57174400-146f-11eb-90a7-538a37babcd7.png)

**Comment by thierryzoller** [comment]
![image](https://user-images.githubusercontent.com/958490/96869371-a8273800-146f-11eb-8b11-bb58cd0e4e34.png)

**Comment by supermerill** [comment]
can i have your project file?

**Comment by thierryzoller** [comment]
[Fanspeed.zip](https://github.com/supermerill/SuperSlicer/files/5423027/Fanspeed.zip)

**Comment by supermerill** [comment]
that's because of the fan startup delay (in the printer tab). It's here to ensure the fan will be at 100% when you'll be at the internal perimeter again.

I created that to ensure the fan will be at full steam when doing bridges and overhangs, as my petg small bridges had a bad tiem without it. But now that we also have fan control for things like external and top, maybe I should restrict it to bridge/overhangs fan speedup only.

**Comment by thierryzoller** [comment]
Interesting, probably it's best placed in the Filament FAN section rather than in the printer ?

If that's the case, why do you think do we have those individual "random" fan speed adjustemnts on these pillars?

![image](https://user-images.githubusercontent.com/958490/96889529-f98ef180-1486-11eb-81fd-132ab408a982.png)

**Comment by thierryzoller** [comment]
The Opposite Pillar has this (They are mirrored 100%)

![image](https://user-images.githubusercontent.com/958490/96889771-3824ac00-1487-11eb-9212-aa5e6401169a.png)
