### ISSUE TITLE
V.2.2 - Settings and Printers Disappear

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#662]
### Version
2.2 Stable

What is happening:
- When I install the new 2.2 stable, some settings error (can't read monotonous) and Printers dissapear. Downgrading to repetier-version, fixes the issue.

- For version 2.3.55 all settings and configs are no longer read and I have a vanilla install.

Note I have Prusa Slicer Installed aswell.

`Failed loading the preset file: C:\Users\thier\AppData\Roaming\SuperSlicer\print\X11.ini
Reason: ConfigBase::set_deserialize() failed for 'bottom_fill_pattern' = 'monotonous'
Failed loading the preset file: C:\Users\thier\AppData\Roaming\SuperSlicer\printer\Artillery SX1.ini
Reason: ConfigBase::set_deserialize() failed for 'host_type' = 'repetier'
Failed loading the preset file: C:\Users\thier\AppData\Roaming\SuperSlicer\printer\Sapphire Pro - No Zhop.ini
Reason: ConfigBase::set_deserialize() failed for 'host_type' = 'repetier'
Failed loading the preset file: C:\Users\thier\AppData\Roaming\SuperSlicer\printer\Sapphire Pro.ini
Reason: ConfigBase::set_deserialize() failed for 'host_type' = 'repetier'`

**Comment by neophyl** [comment]
Cant comment on the 2.2 stable as I haven't downloaded it yet but....

The 2.3.55 I think is in the same boat as the Prusa 2.3.0 alpha releases.  They save all their configs to an alpha directory so that it doesn't impact the configurations of the vanilla released versions.
If you want any custom profiles from 2.2.xx in the 2.3.xx versions then you can export a configuration bundle from the earlier release and then import it into the 2.3.xx release.  That's normal for proper releases and alpha/beta builds.

I did run the 2.3.55 and ran through the wizard to get a basic mk3 installed and the software running and then I imported a saved config bundle I had from 2.2 and it brought through all my custom Print/Filament/Printer profiles.  There was no problems importing those, although I don't use octoprint so didn't have to deal with the new 'Physical' printer changes that have been added to the PS 2.3 alphas that 2.3.55 is merging with.

**Comment by supermerill** [comment]
You can't really downgrade from the 2.3/2.2.54 to the 2.2.53 without these problems, I have to add a dialog to ask for erasing incompatible settings.

For the second problem, it's as neophyl said.

**Comment by thierryzoller** [comment]
Thank you

**Comment by justdanpo** [comment]
I've lost my print and filament settings after running 2.3.55. I've tried restoring settings from backup but that hasn't helped. Are there other settings except SuperSlicer folder in a user profile?

**Comment by supermerill** [comment]
the 2.3.55 branch uses the `superslicer-alpha` directory (because it was using the alpha-then-beta prusaslicer 2.3). Reverted back to `superslicer` in 2.3.56
