### ISSUE TITLE
Bridges being detected as overhang perimeters

### ISSUE THREAD

**Issue by Tinchus2009** [supermerill/SuperSlicer#824]
### Version
2.3.55
### Operating system type + version
win10 

### 3D printer brand / version + firmware version (if known)
custom reprapfirmware

### Behavior
Look at the picture. The perimeter that, I think< should be detected as bridges, are being treated as overhangs. The inner perimeters are treated as bridges as expected.
The problem with this is that the values you expect to be used on briges are not being used on those external perimters.

![bridge](https://user-images.githubusercontent.com/14299602/102806665-0d2dda00-439c-11eb-8e49-ebe1d07c12af.png)

**Comment by 0x4d4e** [comment]
Maybe related - just the other way around: what should be an overhang perimeter is detected as bridge-infill

v2.3.55
![image](https://user-images.githubusercontent.com/91870/111426867-92076600-86f5-11eb-9a44-b67eb8b7f1f1.png)

v2.2.53
![image](https://user-images.githubusercontent.com/91870/111426910-9e8bbe80-86f5-11eb-852b-ae8a7057a42c.png)

**Comment by supermerill** [comment]
@0x4d4e : i need the project file, please.

@Tinchus2009: currently, all unsupported perimeters are set as "overhangs". I can change that so that all continuous strait overhangs are now tagged as "bridge", but that will change some overhangs like the ones in the top of the "//" of the voron cube to be bridges, are they are strait. 

I don't see how I can put them apart. maybe with a third threshold....

**Comment by 0x4d4e** [comment]
@supermerill zipped project file attached. Thanks!

[Voron_Design_Cube_v7_bridge_infill_overhangs.zip](https://github.com/supermerill/SuperSlicer/files/6172588/Voron_Design_Cube_v7_bridge_infill_overhangs.zip)
