### ISSUE TITLE
Gap Fill Very Inconsistent 

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#868]
Win10 x64 / 2.3.55.2

I am having a very hard time getting gap filling to act consistently.

Some areas fill pretty well (green), other areas start to gap fill, stop too early (yellow), some areas don't even try (red), and one area actually had room for one more actual perimeter, but gap filled partially instead (purple).

![image](https://user-images.githubusercontent.com/12439543/104107088-8162eb80-527f-11eb-9389-78cce9c7d3c9.png)

[Servo Arm1.6.3mf.txt](https://github.com/supermerill/SuperSlicer/files/5791690/Servo.Arm1.6.3mf.txt)

**Comment by supermerill** [comment]
Some may be evicted because they are too small, did you try with a very low min area?

Some are more problematic to resolve/display. On the bottom part, you put an arrow on an empty surface, but it's empty because of the way the yellow loop is draw, as it should be filling the are for a width/2 more, like on the right side (wich print fine, because it's making a nice curve vs steep direction change). I'll have to print it with the real polygon to see if there is any missing areas, and by how much.

**Comment by CCS86** [comment]
Yes, I have the gap filling threshold to 30% (of a 0.4mm nozzle), which is quite a bit smaller than default. 

Let me know if I can provide anything else to help.

**Comment by supermerill** [comment]
An exemple of "visual artifact"
![image](https://user-images.githubusercontent.com/6536403/105614088-4efcd680-5dc7-11eb-9eef-337888d6e31b.png)

90% of your issue is that: just that the tip isn't showed / printed.

**Comment by supermerill** [comment]
It's maybe possible to change the way it's sliced to forbid angles sharper than 120°, but it's a big task and I really don't have the time for that.
