### ISSUE TITLE
First perimeter of bridge not working properly

### ISSUE THREAD

**Issue by toskium** [supermerill/SuperSlicer#94]
### Version
1.42.2

### Operating system type + version
Windows 10 Pro 1803

### 3D printer brand / version + firmware version
Hypercube Evolution (DIY)
RRF 2.02

### Behavior
* The very first perimeter of a bridge is sagging down, I suppose the bridging flow is not set. (see photo), all other bridging perimeters work as expected.

* To reproduce this problem print a bridge to your liking. I created a simple test object for that.

* Exptected result is a proper bridge

* Actual Result, see picture
![IMG_20190902_203051](https://user-images.githubusercontent.com/15872792/64157197-93847c80-ce36-11e9-9a9d-0e8019209282.jpg)

**Comment by supermerill** [comment]
This couldn't be because the fan isn't at max speed?
To test it, "disable" the fan for bridges.

**Comment by toskium** [comment]
Unfortunately not, I verified fan speed as this was my first suspicion.
The fan is set to 100% with a 3 second fan startup delay.

**Comment by supermerill** [comment]
I review a simple gcode and for the first perimeter (the inner one), it extrudes at 0.033 mmFil/mmMove in not-bridged area and at 0.042 in bridged area.
It's exactly the same for the second perimeter (middle one).
For the external perimeter, the amount of plastic for not-bridged section is a bit lower (0.314) but it's the same for the bridge (0.042).

So it's not the gcode fault or the bug has been repaired in the meantime.

An other explanation is a big pressure build-up in the nozzle that is release at the first bridge encountered (because it's trying to over-extrude). You may want to lower the filament extrusion ratio if it's the case.
